site_name: ""
site_description: Dokumentation, analyser och handböcker
site_url: https://ChristerNilsson.github.io/SRS_wiki
repo_url: ""
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
nav:
  - Hem: index.md
plugins:
  - search
  - ezlinks
# OBS: Navigeringen kan även genereras automatiskt; lämna nav borttagen om du vill att MkDocs
# listar sidorna efter filstruktur. (Se tips längre ned.)
